[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock


[program:gmetad]
command=/usr/sbin/gmetad
autostart=true
autorestart=true
stdout_logfile=/var/log/gmetad.out.log
stderr_logfile=/var/log/gmetad.err.log

[program:gmond]
command=/usr/sbin/gmond
autostart=true
autorestart=true
stdout_logfile=/var/log/gmond.out.log
stderr_logfile=/var/log/gmond.err.log

[program:php-fpm]
command=/usr/sbin/php-fpm
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.out.log
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[program:httpd]
command=/usr/sbin/httpd -DFOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/httpd.out.log
stderr_logfile=/var/log/httpd.err.log
